In [1]:
#Required Libraries
import pandas as pd  
import numpy as np
from nltk.stem import SnowballStemmer
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Warnings
import warnings
warnings.filterwarnings('ignore')

# Text Preprocessing
import nltk
#nltk.download("all")   # you will need to download it if you have not done so
from nltk.corpus import stopwords
import string
from nltk.tokenize import word_tokenize
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import xgboost
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from lightgbm import LGBMClassifier
import keras
import tensorflow as tf

In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
import numpy
from keras.datasets import imdb
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.layers.core import Dense, Activation, Dropout
from keras.callbacks import ModelCheckpoint, EarlyStopping

In [3]:
data= pd.read_csv('Language.csv')

In [4]:
data['language'].unique()

array(['Estonian', 'Swedish', 'Thai', 'Tamil', 'Dutch', 'Japanese',
       'Turkish', 'Latin', 'Urdu', 'Indonesian', 'Portugese', 'French',
       'Chinese', 'Korean', 'Hindi', 'Spanish', 'Pushto', 'Persian',
       'Romanian', 'Russian', 'English', 'Arabic'], dtype=object)

# Pre-Processing

In [5]:
df=data

In [6]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("english")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('english')]
    
    return " ".join(text)

English_text = df[df['language']=='English']['Text'].apply(stemmer)
English_text = English_text.apply(puncStopW)

In [7]:
df=data

In [8]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("swedish")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('swedish')]
    
    return " ".join(text)

Swedish_text = df[df['language']=='Swedish']['Text'].apply(stemmer)
Swedish_text = Swedish_text.apply(puncStopW)

In [9]:
df=data

In [10]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("dutch")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('dutch')]
    
    return " ".join(text)

Dutch_text = df[df['language']=='Dutch']['Text'].apply(stemmer)
Dutch_text = Dutch_text.apply(puncStopW)

In [11]:
 df=data

In [12]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("french")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('french')]
    
    return " ".join(text)

French_text = df[df['language']=='French']['Text'].apply(stemmer)
French_text = French_text.apply(puncStopW)

In [13]:
df=data

In [14]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("spanish")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('spanish')]
    
    return " ".join(text)

Spanish_text = df[df['language']=='Spanish']['Text'].apply(stemmer)
Spanish_text = Spanish_text.apply(puncStopW)

In [15]:
df=data

In [16]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("romanian")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('romanian')]
    
    return " ".join(text)

Romanian_text = df[df['language']=='Romanian']['Text'].apply(stemmer)
Romanian_text = Romanian_text.apply(puncStopW)

In [17]:
df=data

In [18]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("russian")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('russian')]
    
    return " ".join(text)

Russian_text = df[df['language']=='Russian']['Text'].apply(stemmer)
Russian_text = Russian_text.apply(puncStopW)

In [19]:
df=data

In [20]:
def stemmer(text):
    text = text.split()
    words = ""
    for i in text:
            stemmer = SnowballStemmer("arabic")
            words += (stemmer.stem(i))+" "
    return words

def puncStopW(text):
    
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = [word for word in text.split() if word.lower() not in stopwords.words('arabic')]
    
    return " ".join(text)

Arabic_text = df[df['language']=='Arabic']['Text'].apply(stemmer)
Arabic_text = Arabic_text.apply(puncStopW)

In [21]:
data_new=pd.DataFrame(columns=['Text','language'])

In [22]:
languages=['Arabic','Russian','Romanian','Spanish','French','Dutch','Swedish','English']
temp=[Arabic_text,Russian_text,Romanian_text,Spanish_text,French_text,Dutch_text,Swedish_text,English_text]
for i in range(0,8):
    for x in temp[i]:
        data_new = data_new.append({'Text': x,'language':languages[i]},ignore_index=True)

In [23]:
data_new.shape

(8000, 2)

In [24]:
data_new

Text language
0     عام ضبط تاريخ اعل بغداد خط هدم اسوار تاريخ هاج...   Arabic
1     عندم وصل جنود حمل فرنس غرب مدين اسكندر يول عام...   Arabic
2     بصو الشج مميز خطيب مميز صاحب مدرس طور قل تجد م...   Arabic
3     ليل دخل مسلح داعش مدين رماد عاصم محافظ انبار و...   Arabic
4     درج خط طول مقسم الى دقيق ينقسم الى يتم كتاب خط...   Arabic
...                                                 ...      ...
7995  march empti mirror press publish epstein polit...  English
7996  musk want go mar back human worthi goal lot em...  English
7997  overal male black abov white also white superc...  English
7998  tim reynold born decemb wiesbaden germani gram...  English
7999  total high school popul approach committe conc...  English

[8000 rows x 2 columns]

In [25]:
from sklearn.utils import shuffle
data_new = shuffle(data_new)
data_new = shuffle(data_new)

In [26]:
#transforming a text into a vector on the basis of the frequency (count) of each word that occurs in the entire text.
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
vec.fit(data_new["Text"])
features_np = vec.transform(data_new["Text"]).toarray()

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(data_new['language'])

# Data Partition for Traditional Machine Learning Models

In [28]:
#Splitting data into 70% training data and 30% testing data using stratify
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features_np,y,
                                          test_size=0.3, random_state=1,
                                            stratify=data_new['language'])

### Multinomial NB Model

In [34]:
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_hat=clf.predict(X_test)
a=accuracy_score(y_test,y_hat)
print('The accuracy score using MultinomialNB is {}%'.format(a*100))
print("The confusion matrix is:")
print(confusion_matrix(y_test, y_hat))
print("The precision score is:")
print(precision_score(y_test, y_hat, average='weighted'))
print("The recall score is:")
print(recall_score(y_test, y_hat, average='weighted'))

The accuracy score using MultinomialNB is 99.5%
The confusion matrix is:
[[298   1   1   0   0   0   0   0]
 [  1 298   0   1   0   0   0   0]
 [  0   0 299   0   0   0   0   1]
 [  0   0   1 297   1   0   0   1]
 [  0   1   0   0 299   0   0   0]
 [  0   0   0   1   1 297   0   1]
 [  0   0   0   0   0   0 300   0]
 [  0   0   0   0   0   0   0 300]]
The precision score is:
0.9950137327341774
The recall score is:
0.995


In [40]:
test_data=['صباح الخير.']
test_input = vec.transform(test_data).toarray()
y_hat=clf.predict(test_input)
predictions = encoder.inverse_transform(y_hat)
predictions

array(['Arabic'], dtype='<U8')

### LogisticRegression  Model

In [41]:
#Applying LogisticRegression classifier
logistic_model = LogisticRegression(random_state=0).fit(X_train, y_train)
y_hat=logistic_model.predict(X_test)
a=accuracy_score(y_test,y_hat)
print('The accuracy score using Logistic is {}%'.format(a*100))
print("The confusion matrix is:")
print(confusion_matrix(y_test, y_hat))
print("The precision score is:")
print(precision_score(y_test, y_hat,average='weighted'))
print("The recall score is:")
print(recall_score(y_test, y_hat, average='weighted'))

The accuracy score using Logistic is 98.95833333333334%
The confusion matrix is:
[[299   0   0   0   1   0   0   0]
 [  0 295   2   0   0   0   3   0]
 [  0   0 299   0   0   0   0   1]
 [  0   2   0 295   1   0   2   0]
 [  0   1   2   2 293   0   2   0]
 [  0   0   0   1   0 297   2   0]
 [  0   0   1   1   0   0 298   0]
 [  0   0   0   0   1   0   0 299]]
The precision score is:
0.9896653952103827
The recall score is:
0.9895833333333334


In [45]:
test_data=['¿Cómo te llamas ']
test_input = vec.transform(test_data).toarray()
y_hat=logistic_model.predict(test_input)
predictions = encoder.inverse_transform(y_hat)
predictions

array(['Spanish'], dtype='<U8')

### XGBoost  Model

In [46]:
#Applying XGBoost classifier
xgbc = XGBClassifier()
xgbc.fit(X_train, y_train)
y_hat=xgbc.predict(X_test)
a=accuracy_score(y_test,y_hat)
print('The accuracy score using KNeighborsClassifier is {}%'.format(a*100))
print("The confusion matrix is:")
print(confusion_matrix(y_test, y_hat))
print("The precision score is:")
print(precision_score(y_test, y_hat, average='weighted'))
print("The recall score is:")
print(recall_score(y_test, y_hat, average='weighted'))

[14:30:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
The accuracy score using KNeighborsClassifier is 95.875%
The confusion matrix is:
[[294   1   4   0   1   0   0   0]
 [  0 283  12   1   0   0   4   0]
 [  0   0 293   5   1   0   0   1]
 [  0   3   9 282   0   0   4   2]
 [  0   1   8   1 284   0   6   0]
 [  0   0   9   1   0 288   2   0]
 [  0   0   8   4   1   0 287   0]
 [  0   1   6   1   1   0   1 290]]
The precision score is:
0.9618329569528411
The recall score is:
0.95875


In [53]:
test_data=['How are you? ']
test_input = vec.transform(test_data).toarray()
y_hat=xgbc.predict(test_input)
predictions = encoder.inverse_transform(y_hat)
predictions

array(['English'], dtype='<U8')

### RandomForestClassifier  Model

In [54]:
#Applying RandomForestClassifier classifier
RandomForestClassifier_model = RandomForestClassifier(max_depth=10, random_state=0)
RandomForestClassifier_model.fit(X_train, y_train)
y_hat=RandomForestClassifier_model.predict(X_test)
a=accuracy_score(y_test,y_hat)
print('The accuracy score using RandomForestClassifier_model is {}%'.format(a*100))
print("The confusion matrix is:")
print(confusion_matrix(y_test, y_hat))
print("The precision score is:")
print(precision_score(y_test, y_hat, average='weighted'))
print("The recall score is:")
print(recall_score(y_test, y_hat, average='weighted'))

The accuracy score using RandomForestClassifier_model is 93.16666666666666%
The confusion matrix is:
[[289   0  11   0   0   0   0   0]
 [  0 267  28   1   0   0   1   3]
 [  0   1 291   3   4   0   0   1]
 [  0   0  15 280   2   0   3   0]
 [  0   0  10   1 285   0   2   2]
 [  0   0  13   1   1 284   1   0]
 [  0   0  19   3   1   0 277   0]
 [  0   3  28   3   1   0   2 263]]
The precision score is:
0.9451203965230536
The recall score is:
0.9316666666666666


### KNeighborsClassifier  Model

In [ ]:
 for i in range(1,30):
        neigh = KNeighborsClassifier(n_neighbors=i)
        neigh.fit(X_train, y_train)
        y_hat=neigh.predict(X_test)
        a=accuracy_score(y_test,y_hat)
        print('The accuracy score using KNeighborsClassifier is {}%'.format(a*100))
        print("The confusion matrix is:")
        print(confusion_matrix(y_test, y_hat))
        print("The precision score is:")
        print(precision_score(y_test, y_hat, average='weighted'))
        print("The recall score is:")
        print(recall_score(y_test, y_hat, average='weighted'))


The accuracy score using KNeighborsClassifier is 52.79166666666667%
The confusion matrix is:
[[118   0   0 182   0   0   0   0]
 [  0 135   0 163   2   0   0   0]
 [  0   0 129 171   0   0   0   0]
 [  0   1   0 295   1   1   2   0]
 [  0   0   0 147 151   1   1   0]
 [  0   0   0 174   0 126   0   0]
 [  0   0   0 195   1   0 104   0]
 [  0   1   1  88   1   0   0 209]]
The precision score is:
0.888809506537985
The recall score is:
0.5279166666666667
The accuracy score using KNeighborsClassifier is 53.625%
The confusion matrix is:
[[158   0   0 142   0   0   0   0]
 [  0 204   1  95   0   0   0   0]
 [  0   3 192 105   0   0   0   0]
 [  0   2   5 290   1   1   1   0]
 [  0   1   1 189 109   0   0   0]
 [  0   0   0 219   0  81   0   0]
 [  0   2   0 235   1   0  62   0]
 [  0   2   1 104   1   0   1 191]]
The precision score is:
0.8816671885870939
The recall score is:
0.53625
The accuracy score using KNeighborsClassifier is 60.70833333333333%
The confusion matrix is:
[[119   0   0 18

# Pre-Processing for ANN model

In [31]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

#Fit encoder
encoder = LabelEncoder()
encoder.fit(['Arabic','Russian','Romanian','Spanish','French','Dutch','Swedish','English'])
y_encoded = encoder.transform(data_new['language'])
y_dummy = np_utils.to_categorical(y_encoded)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(features_np,y_dummy,
                                          test_size=0.3, random_state=1,stratify=y_dummy)

# DNN Model

In [29]:
model = Sequential()
model.add(Dense(500,input_dim=X_train.shape[1],activation="sigmoid"))
model.add(Dropout(0.5))
model.add(Dense(300,activation="sigmoid"))
model.add(Dropout(0.5))
model.add(Dense(100,activation="sigmoid"))
model.add(Dropout(0.5))
model.add(Dense(8,activation="softmax"))
model_optimizer = tf.keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='categorical_crossentropy',
              optimizer=model_optimizer,
              metrics=['accuracy'])

In [30]:
history = model.fit(X_train,y_train,
          validation_split=0.10,epochs=10,
          batch_size=64,
          verbose=2,
          shuffle=True)

Epoch 1/10
88/88 - 15s - loss: 2.1069 - accuracy: 0.1918 - val_loss: 1.8707 - val_accuracy: 0.3125 - 15s/epoch - 172ms/step
Epoch 2/10
88/88 - 12s - loss: 1.5430 - accuracy: 0.4545 - val_loss: 0.8748 - val_accuracy: 0.9696 - 12s/epoch - 139ms/step
Epoch 3/10
88/88 - 11s - loss: 0.6466 - accuracy: 0.8431 - val_loss: 0.1808 - val_accuracy: 0.9984 - 11s/epoch - 127ms/step
Epoch 4/10
88/88 - 12s - loss: 0.2263 - accuracy: 0.9665 - val_loss: 0.0668 - val_accuracy: 1.0000 - 12s/epoch - 134ms/step
Epoch 5/10
88/88 - 11s - loss: 0.1140 - accuracy: 0.9868 - val_loss: 0.0317 - val_accuracy: 1.0000 - 11s/epoch - 126ms/step
Epoch 6/10
88/88 - 12s - loss: 0.0643 - accuracy: 0.9932 - val_loss: 0.0198 - val_accuracy: 1.0000 - 12s/epoch - 132ms/step
Epoch 7/10
88/88 - 11s - loss: 0.0469 - accuracy: 0.9954 - val_loss: 0.0142 - val_accuracy: 1.0000 - 11s/epoch - 128ms/step
Epoch 8/10
88/88 - 11s - loss: 0.0341 - accuracy: 0.9984 - val_loss: 0.0094 - val_accuracy: 1.0000 - 11s/epoch - 127ms/step
Epoch 9/

In [63]:
test_data=['I am good']
test_input = vec.transform(test_data).toarray()
labels = np.argmax(model.predict(test_input), axis=-1) #model.predict(X_test)
predictions = encoder.inverse_transform(labels)

In [64]:
test_input.shape

(1, 63105)

In [66]:
predictions

array(['Dutch'], dtype='<U8')

In [39]:
test_input

array([[1, 1, 1]], dtype=int64)

In [ ]:
print(round(train_acc[1]*100,2))
print(round(val_acc[1]*100,2))
print('The training accuracy for AN is {}%'.format(round(train_acc[1]*100,2)))
print('The testing accuracy for AN is {}%'.format(round(val_acc[1]*100,2)))

In [ ]:
max_review_length = 500
top_words = 5000
embedding_vecor_length = 32
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Implementation LSTM Model

In [ ]:
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(1000, embedding_vecor_length, input_length=X_train.shape[1]))
model.add(LSTM(2, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, epochs=3, batch_size=64)

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
train_acc = model.evaluate(X_train, y_train)
val_acc = model.evaluate(X_test, y_test)
print('The training accuracy for N-Grams is {}%'.format(round(train_acc[1]*100,2)))
print('The testing accuracy for N-Grams is {}%'.format(round(val_acc[1]*100,2)))

# Data Pre-Processing for N-Gram

In [ ]:
def get_trigrams(corpus,n_feat=200):
    """
    Returns a list of the N most common character trigrams from a list of sentences
    params
    ------------
        corpus: list of strings
        n_feat: integer
    """
    
    #fit the n-gram model
    vectorizer = CountVectorizer(analyzer='char',
                            ngram_range=(4, 4)
                            ,max_features=n_feat)
    
    X = vectorizer.fit_transform(corpus)
    
    #Get model feature names
    feature_names = vectorizer.get_feature_names()
    
    return feature_names

In [ ]:
#obtain trigrams from each language
features = {}
features_set = set()

for l in languages:
    
    #get corpus filtered by language
    corpus = data_new[data_new.language==l]['Text']
    
    #get 200 most frequent trigrams
    trigrams = get_trigrams(corpus)
    
    #add to dict and set
    features[l] = trigrams 
    features_set.update(trigrams)

    
#create vocabulary list using feature set
vocab = dict()
for i,f in enumerate(features_set):
    vocab[f]=i

In [ ]:
#train count vectoriser using vocabulary
vectorizer = CountVectorizer(analyzer='char',
                             ngram_range=(4, 4),
                            vocabulary=vocab)

#create feature matrix for training set
corpus = data_new['Text']   
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names()

features_np = pd.DataFrame(data=X.toarray(),columns=feature_names)

In [ ]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

encoder = LabelEncoder()
encoder.fit(['Arabic','Russian','Romanian','Spanish','French','Dutch','Swedish','English'])
y_encoded = encoder.transform(data_new['language'])
y_dummy = np_utils.to_categorical(y_encoded)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_np,y_dummy,
                                          test_size=0.15,stratify=y_dummy)

# Implementation of N-Gram DNN model

In [ ]:
model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation='sigmoid'))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(16, activation='sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(8, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=64) #fit ANN

In [ ]:
train_acc = model.evaluate(X_train, y_train)
val_acc = model.evaluate(X_test, y_test)
print('The training accuracy for N-Grams is {}%'.format(round(train_acc[1]*100,2)))
print('The testing accuracy for N-Grams is {}%'.format(round(val_acc[1]*100,2)))